version: 0.5.{build}
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    PROJECT_NAME: "krypto"
    RELEASE_BRANCH: "release"
    CONAN_USERNAME: "klusekrules"
    CONAN_LOGIN_USERNAME: "klusekrules"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/klusekrules/klusekrules"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - set CONAN_REFERENCE=%PROJECT_NAME%/%APPVEYOR_BUILD_VERSION%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

build_script:
  - conan source . --source-folder=tmp
  - conan install . --install-folder=tmp
  - conan build . --source-folder=tmp --install-folder=tmp --build-folder=tmp

test_script:
  - conan export-pkg . %CONAN_USERNAME%/%CONAN_CHANNEL% --source-folder=tmp --install-folder=tmp --build-folder=tmp
  - conan test test_package %CONAN_REFERENCE%@%CONAN_USERNAME%/%CONAN_CHANNEL%

deploy_script:
- cmd: >-
    IF %APPVEYOR_REPO_BRANCH% EQU %RELEASE_BRANCH% (python build.py) ELSE (Echo Deploy is canceled, not release branch selected)